### ISSUE TITLE
Question: Linked services

### ISSUE THREAD

**Issue by Korcsog** [maximkulkin/esp-homekit#100]
Hi!

Linked services are available? Actually i'm working on a multi zone Irrigation system, which needs multiple Valve services linked to an Irrigation service! Same logic applies to the (heated) Shower accessory, Valve service assigned to target temp characteristic!  Is there any way to do this?

![Képernyőfotó 2019-07-29 - 14 28 20](https://user-images.githubusercontent.com/19993757/62048473-45fc6a80-b20d-11e9-8b8f-38b01c6a0582.png)

Thanks!

**Comment by maximkulkin** [comment]
Yes, you can use linked services. Here is an example: https://github.com/maximkulkin/esp-ir-tv/blob/master/main/main.c#L226-L231

**Comment by Korcsog** [comment]
Great thanks! 😉
