### ISSUE TITLE
Accessory code

### ISSUE THREAD

**Issue by ericklil** [maximkulkin/esp-homekit#102]
Thank you for your work!

If I wanted to change the `accessory` to say a Light with `HSV` values, Or make this control a fan with speed, direction etc, basically adding `characteristics` to the `accessory`. How would one find the setup code for that.

**Comment by maximkulkin** [comment]
Well, to implement an accessory you need to add apropriate *services* which in turn have proper *characteristics*. Setup codes are either hard-coded inside firmware (and printed somewhere on packaging or on the accessory itself),
![iDevices-HomeKit-Code-768x407](https://user-images.githubusercontent.com/10785/63306964-877ab580-c2a1-11e9-920e-f892922ea0b6.jpg)

![SF278428-002_EN_v3](https://user-images.githubusercontent.com/10785/63306959-821d6b00-c2a1-11e9-8b59-172d3c094107.png)



or you add a screen to accessory and show randomly generate setup code or even QR code.

![IMG_0077](https://user-images.githubusercontent.com/10785/63306803-fdcae800-c2a0-11e9-92be-d6b63fc20623.JPEG)

![IMG_0076](https://user-images.githubusercontent.com/10785/63306796-f7d50700-c2a0-11e9-9968-25d0b7cb33f4.JPEG)

**Comment by ericklil** [comment]
Thank you for your quick reply, I erred in my question
I meant to ask; how to create an accessory other than the sample you provided. i.e a Light with HSV values such as a Neopixel or a Fan with speed, direction and other `characteristics or services`?
Where to find the `accessory category code` as you mention in your`readme.md`
In the sample is the `.setupId="1QJ8"`  random generated?

**Comment by maximkulkin** [comment]
Well, the main read is [Homekit Accessory Protocol Specification](https://developer.apple.com/homekit/specification/) (you need to create an Apple Developer account to access it). You can find it on this page: https://developer.apple.com/homekit/

In esp-homekit all services and characteristics for the spec are defined in [homekit/characteristics.h](https://github.com/maximkulkin/esp-homekit/blob/master/include/homekit/characteristics.h). For convenience, service definitions in that header file are provided with list of required and optional characteristics.
