### ISSUE TITLE
QR Code Tools PAYLOAD FLAGS correction

### ISSUE THREAD

**Issue by izone-airstream** [maximkulkin/esp-homekit#104]
I think there is a minor error in the comment. That for PAYLOAD_FLAGS should IP_WAC=10.

**Comment by maximkulkin** [comment]
It would be much easier to address this kind of issues if you would include proofs (e.g. screenshot from HomeKit Simulator or reference to documentation) since I assume you've used those to report it. Otherwise it takes me time to pull stuff up and re-verify everything.
