### ISSUE TITLE
Espressif FreeRTOS for 8266 compatibility

### ISSUE THREAD

**Issue by salas81** [maximkulkin/esp-homekit#113]
Does this library work with Espressif FreeRTOS for 8266 or only with  ESP-OPEN-RTOS?

**Comment by maximkulkin** [comment]
It does, although some examples need to be adjusted to work with ESP8266_RTOS_SDK

**Comment by peros550** [comment]
what is the advantage of using Espressif FreeRTOS over ESP-OPEN-RTOS?

**Comment by d4rkmen** [comment]
@peros550  First: this is official SDK that keeps updating, while OPEN-RTOS uses some old compiled official binaries due to license restrictions.
Second: I faces remote access problems with OPEN-RTOS and RTOS-SDK works fine for me.

**Comment by peros550** [comment]
Maxim, what’s your view on this case?
