### ISSUE TITLE
EEPROM

### ISSUE THREAD

**Issue by vvrec** [maximkulkin/esp-homekit#137]
If I understand correctly - EEPROM can not be used in the main sketch?
Or are only certain addresses available for read/write?

**Comment by maximkulkin** [comment]
I assume, by EEPROM you mean flash. Yes, you can write to any address, but as far as I understand there is some kind of protection of current running code (although it might differ from SDK to SDK).

**Comment by vvrec** [comment]
Yes, I mean memory. The problem is that if I use EEPROM.h to remember the last brightness value - after several complete shutdowns and power-ups of the board Home.app on the phone forgets this device. But I can add it again.
