### ISSUE TITLE
Combine button and temperature sensor

### ISSUE THREAD

**Issue by brisbaneeastcoast** [maximkulkin/esp-homekit#146]
Hi,

I'm trying to combine the button project and the temperature_sensor project. 
I copied everthing from the build directory of the temperature_sensor project to the build folder of the button project. 
If I try to upload, the compiler says:
fatal error: No such dile or directory #include<button.h>

Do I have to update some build settings or something like that ?

Whould be great if someone can help me with this problem. 
![Unbenannt](https://user-images.githubusercontent.com/65179037/81578994-e0e4c080-93ab-11ea-983c-237903f9d5e6.PNG)

**Comment by maximkulkin** [comment]
Button example depends on [esp-button](https://github.com/maximkulkin/esp-button) library which you need to [depend upon in Makefile](https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/button/Makefile#L5)

**Comment by brisbaneeastcoast** [comment]
Thank you I just forgot the lines in the makefile.
