### ISSUE TITLE
error

### ISSUE THREAD

**Issue by coffice12** [maximkulkin/esp-homekit#155]
code：
 HOMEKIT_SERVICE(HEATER_COOLER, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "HEATER_COOLER"),
            HOMEKIT_CHARACTERISTIC(
                COOLING_THRESHOLD_TEMPERATURE, HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED,
                .getter=NULL,
                .setter=NULL
            ),

if config COOLING_THRESHOLD_TEMPERATURE

will not connect esp homekit

**Comment by beckmx** [comment]
I guess, (I am not sure) but according to the other examples you are declaring two characteristics in 1, have you tried separating them?
`
HOMEKIT_CHARACTERISTIC(HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED, 0),
HOMEKIT_CHARACTERISTIC(
COOLING_THRESHOLD_TEMPERATURE, 
.getter=NULL,
.setter=NULL
),`

**Comment by coffice12** [comment]
HOMEKIT_CHARACTERISTIC( COOLING_THRESHOLD_TEMPERATURE, .getter=NULL, .setter=NULL ),

error:


error: expected expression before '.' token
                 .getter=NULL,

**Comment by maximkulkin** [comment]
@coffice12 What is this supposed to mean?
```c
HOMEKIT_CHARACTERISTIC(
COOLING_THRESHOLD_TEMPERATURE, HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED
);
```

When you're designing an accessory it makes sense to 1) check [HAP specification](https://developer.apple.com/homekit/specification/) on a service you might need for a job (go to "Apple-defined Services" chapter); or 2) check your [service definition comment](https://github.com/maximkulkin/esp-homekit/blob/master/include/homekit/characteristics.h#L603-L625) inside the esp-homekit to know which characteristics are required; 3) check [characteristic definition](https://github.com/maximkulkin/esp-homekit/blob/master/include/homekit/characteristics.h#L743-L756) for formats and value ranges. In your case value HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED ("1") is outside of default allowed range for COOLING_THRESHOLD_TEMPERATURE (10-35).

**Comment by coffice12** [comment]
Problem solved，thank you！！
