### ISSUE TITLE
CURL - debug

### ISSUE THREAD

**Issue by awasspl** [maximkulkin/esp-homekit#187]
Hi guys,

Hi can i check accessories list with curl command?
Somethink like: 

` curl -X GET http://192.168.0.111:5556/accessories --header "Content-Type:Application/json" --header "authentication: "111-11-111"" -s`

i make some mistake i think and still getting accessory "not compatible" :(

**Comment by maximkulkin** [comment]
Ahaha, no no no no. That does not work like that. For debugging what went wrong, the easiest approach is to enable debug logging, the capturing json response from there. Response usually scattered across several HTTP chunks, so you'll have to do a bit of copy-pasting and concatenation.

**Comment by awasspl** [comment]
it's a pity :( was be easier to just check services and accessories hierarchie.
I remember it was posible with non secure connection. now i don't know how to send auth header.
