### ISSUE TITLE
Can this be used as a proxy for the Level Lock?

### ISSUE THREAD

**Issue by nmajin** [maximkulkin/esp-homekit#206]
I would like to get my Level Lock into Home Assistant and unfortunately cannot use bluetooth with my HA instance. Therefore, could this be utilized to interface or proxy to the Level Lock and then I can tie an ESP32 into HA?

A similar concept that I use today would be https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32 with a SwitchBot device so the ESP32 is communicating with the SwitchBot and then that is integrated with HA via MQTT.

**Comment by maximkulkin** [comment]
If you can implement communication with Level Lock and replicate all HomeKit services and characteristics that it exposes, then yes.
