### ISSUE TITLE
Port on Arduino Core for ESP8266

### ISSUE THREAD

**Issue by pburgio** [maximkulkin/esp-homekit#32]
Hello,

Do you think it is possible to have this library as standalone component (a library, precisely) to embed into another kernel for ESP8266, such as for instance [Arduino Core](https://github.com/esp8266/Arduino)?

We want to use it in our devices, but we don't plan to change the underlying kernel

Best regards
Paolo

**Comment by maximkulkin** [comment]
No plans, sorry
