### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by korstiaanS** [maximkulkin/esp-homekit#44]
Hi,

I want to generate QR codes for the devices I make.
I could use the Homekit simulator to fill in all the exact values and this program will generate the QR code I could use.
In the ESP HomeKit code I find all the necessary fields (Name, Manufacturer, Serial, Model, Password, ...) except something for the SETUP ID. I suppose I need this setup ID field in the ESP as well.
Is that field available and/or can this be added?

Korstiaan

**Comment by korstiaanS** [comment]
This is the simulator:

![image](https://user-images.githubusercontent.com/20791560/39175994-f538e834-47ab-11e8-8614-73e63f7c1041.png)

**Comment by renssies** [comment]
Using the simulator wouldn't work if you knew the Setup ID. The code needs to generate a certain hash that is broadcasted, this is currently not in the code. 

@cduvenhorst was working on implementing it into esp-homekit: https://github.com/maximkulkin/esp-homekit/pull/33

**Comment by korstiaanS** [comment]
Ah, ok. Sorry. I didn't knew it was that complicated.
Thanks for the answer.
It was a nice thing to have (and show off)...

**Comment by royfocker19** [comment]
@korstiaanS, what'sthe name of that simulator.? Where can I download it?

**Comment by korstiaanS** [comment]
@royfocker19 : it is called HomeKit Accessory Simulator. It is from Apple and can be downloaded from the Apple Developer Site. See [here](https://stackoverflow.com/questions/49004759/how-to-use-home-kit-accessory-simulator)

**Comment by fmoreni** [comment]
Hello, my friend,

I did not find on the apple website the qrcode simulator, did you get it where?

Could you help please?

**Comment by cduvenhorst** [comment]
Since Xcode 8 the HomeKit Accessory Simulator is provided with “Additional Tools for Xcode”. https://developer.apple.com/download/more/?=for%20Xcode

**Comment by AramVartanyan** [comment]
You can also use this way:

[HomeKit Codes.zip](https://github.com/maximkulkin/esp-homekit/files/2475344/HomeKit.Codes.zip)

It works for me.

**Comment by maximkulkin** [comment]
Added support for QR code pairing, see [QR code pairing](https://github.com/maximkulkin/esp-homekit/tree/master#qr-code-pairing).
