### ISSUE TITLE
implicit declaration of function 'HOMEKIT_DECLARE_CHARACTERISTIC_SELECTED_RTPS_CONFIGURATION'

### ISSUE THREAD

**Issue by jonkofee** [maximkulkin/esp-homekit#52]
How setup camera?

Please help

**Comment by maximkulkin** [comment]
Well, I guess nobody ever tried to set up camera with this framework, because I guess there is no way to connect camera and/or enough resources to stream video through ESP8266.

Why do you need this?

**Comment by jonkofee** [comment]
I want watching my door

**Comment by maximkulkin** [comment]
Ok, I guess you know what you're doing and the only issue you have is with missing characteristic declaration which I can help you with. So, according to Homekit Accessory Protocol specification the name of characteristic you're looking for is "SELECTED_RTP_STREAM_CONFIGURATION" (not "SELECTED_RTPS_CONFIGURATION"). The comment in our header file is incorrect and I will update it.
