### ISSUE TITLE
ESP32 branch is missing Kconfig

### ISSUE THREAD

**Issue by ruudk** [maximkulkin/esp-homekit#53]
I tried to add it manually to the `esp-homekit` folder but it doesn't gets picked up when I run `make menuconfig`

**Comment by maximkulkin** [comment]
ESP32 support is already merged into master. I have removed obsolete esp32 branch to avoid confusion. See ESP32 instructions in [esp-homekit-demo](https://github.com/maximkulkin/esp-homekit-demo) repository.
