### ISSUE TITLE
mdnsresponder.c is not excluded when compiling for ESP32

### ISSUE THREAD

**Issue by ruudk** [maximkulkin/esp-homekit#56]
It turns out, that the only way to get this to compile for ESP32 is to manually remove `mdnsresponder.c` and `mdnsresponder.h`. 

For some reason this line of code is ignored, any idea why?

https://github.com/maximkulkin/esp-homekit/blob/09e2ed75193eec63bf9c467a0c71bbc4b4eb4140/component.mk#L86

**Comment by maximkulkin** [comment]
Not sure what happened since then, but now it works no problem. Closing
