### ISSUE TITLE
Has anyone tried any hardware/accessory implementation for a camera?

### ISSUE THREAD

**Issue by royfocker19** [maximkulkin/esp-homekit#57]
I was able to make it work using hap node with a raspberry as a node, but I was wondering if it's possible to write an accessory and create the hardware for that.

**Comment by maximkulkin** [comment]
Yes, I'm working on camera implementation in this repository: https://github.com/maximkulkin/esp32-homekit-camera. The work is still in progress (no live streaming support). You're welcome to contribute.
