### ISSUE TITLE
 Error reading data from socket (code 113)

### ISSUE THREAD

**Issue by konifer44** [maximkulkin/esp-homekit#58]
```
I (143392) wifi: n:11 0, o:11 2, ap:255 255, sta:11 2, prof:1
!!! HomeKit: [Client 55] Error reading data from socket (code 113). Disconnecting
STA disconnected
>>> HomeKit: [Client 55] Closing client connection
```

What does it mean? This error occurs while normal usage.

**Comment by curla92** [comment]
> ```
> I (143392) wifi: n:11 0, o:11 2, ap:255 255, sta:11 2, prof:1
> !!! HomeKit: [Client 55] Error reading data from socket (code 113). Disconnecting
> STA disconnected
> >>> HomeKit: [Client 55] Closing client connection
> ```
> 
> What does it mean? This error occurs while normal usage.

how do you resolve it? thank y
