### ISSUE TITLE
Magic Home

### ISSUE THREAD

**Issue by AustinRobinson** [maximkulkin/esp-homekit#65]
I'm trying to upload to a magic home led strip controller and on boot it outputs

>>> HomeKit: Starting server
!!! HomeKit: Failed to read flash magic
>>> HomeKit: Formatting flash at 0x100000
!!! HomeKit: Failed to erase flash
>>> HomeKit: Generated new accessory ID: E3:07:15:6F:9F:3E
!!! HomeKit: Failed to write accessory ID to flash
>>> HomeKit: Generated new accessory key
!!! HomeKit: Failed to write accessory key to flash

**Comment by maccoylton** [comment]
what's the hardware version of the controller you are flashing? 

BTW this looks like it could be some kind of hardware issue, can you try flashing the original firmware back to the device and see if it still works?

**Comment by AustinRobinson** [comment]
From what I have read, the version I have uses an ESP8285.
