### ISSUE TITLE
Magic Home LED Strip Controller

### ISSUE THREAD

**Issue by AustinRobinson** [maximkulkin/esp-homekit#66]
After I upload code to the magic home controller it outputs the following and I can't pair any devices.

```
>>> HomeKit: Starting server
!!! HomeKit: Failed to read flash magic
>>> HomeKit: Formatting flash at 0x100000
!!! HomeKit: Failed to erase flash
>>> HomeKit: Generated new accessory ID: E3:07:15:6F:9F:3E
!!! HomeKit: Failed to write accessory ID to flash
>>> HomeKit: Generated new accessory key
!!! HomeKit: Failed to write accessory key to flash
Function called without core lock

Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
```

**Comment by AustinRobinson** [comment]
By the way sorry for posting three of the same issues, something was wrong with my internet and it was telling me there was an error creating the issue and I just realized all three were actually posted.

**Comment by maximkulkin** [comment]
It looks like you're using a module with flash size of 1Mb or less. In that case you need to modify address where HomeKit stores it's data on Flash. Try this (from [esp-homekit-demo instructions](https://github.com/maximkulkin/esp-homekit-demo)):
```
export FLASH_SIZE=8
export HOMEKIT_SPI_FLASH_BASE_ADDR=0x7a000
make -C examples/led all
```

Feel free to reopen this issue if that does not help (but make sure you provide new logs).
