### ISSUE TITLE
Can't compile after moving tlv.h

### ISSUE THREAD

**Issue by pbendersky** [maximkulkin/esp-homekit#69]
After the move of [tlv.h](https://github.com/maximkulkin/esp-homekit/commit/8da13b1608f662743054a8749d5646dcb4d7afc1) to the include folder, when I try to compile, I get this error:

`make: *** No rule to make target '/esp/components/homekit/src/tlv.h', needed by 'build/homekit//src/tlv.o'.  Stop.`

Is any change in the Makefile needed?

**Update**: I can work around this by adding an empty `tlv.h` in the same directory `tlv.c` resides, but I shouldn't have to. I'm using an ESP8266 (I figure it's relevant, since the project supports two toolchains).

**Comment by maximkulkin** [comment]
You should do a clean build. Just delete build/ directory and compile again.
