### ISSUE TITLE
 iOS says "no response"

### ISSUE THREAD

**Issue by kosukekurimoto** [maximkulkin/esp-homekit#71]
What does that error mean? It occurs about 60-180min after program start.
After few minutes iOS says "no response"
(ESP32-DevKitC)
```
!!! HomeKit: [Client 56] Error reading data from socket (code 113). Disconnecting
>>> HomeKit: [Client 56] Closing client connection
```

**Comment by maximkulkin** [comment]
Erro code 113 is "host unreachable". That might be unrelated issues (e.g. old connection times out and you see error in log and also mDNS advertisement expires). When that happens, can you check if mDNS is still in place (unfortunately, I work only on Macs. On Mac you need to run `dns-sd -B _hap._tcp local` and make sure you see something like this:
```
18:20:20.848  Add        2  10 local.               _hap._tcp.           My Device Name
```
Then check information associated with advertisement:
`dns-sd -L My\ Device\ Name _hap._tcp local`

**Comment by kosukekurimoto** [comment]
Thank you for the hint.
I will continue to investigate.
