### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by AustinRobinson** [maximkulkin/esp-homekit#76]
I have had the LED example running on my esp8266 fro over a week and it usually works just fine. But sometimes in the Home app it will say either Not Responding or Unavailable. This still occurs if I reboot my iPhone. But after somewhere between 10-15 minutes, it starts working fine again. Also I never have had to power cycle the esp8266.

**Comment by maximkulkin** [comment]
That is very subtle problem: iOS has very obscure rules on when to retry accessory connection if it fails. In my setup I helieve it’s even more obscure, becase I have Apple TV that acts as a HomeKit hub, so you’re never sure if e.g. iPhone does not want to connect to accessory even after restart (it might be that it just reads failed state from Apple TV).
