### ISSUE TITLE
ESP8266 - input pins - Handle Interrupts

### ISSUE THREAD

**Issue by kunjal83** [maximkulkin/esp-homekit#80]
Hi, 
Can anyone help me understand if there is a possibility of handling interrupts via pins on ESP8266? 

Thanks,
K

**Comment by maximkulkin** [comment]
You can handle pin changes with interrupts like this:
https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/sonoff_basic/button.c#L80
