### ISSUE TITLE
Negative values in characteristic "CurrentTemperature"

### ISSUE THREAD

**Issue by GermanSheepDog** [maximkulkin/esp-homekit#86]
Hello,
I have been working on a temperature sensors for a freezer and I found that negative temperatures did not appear on my homekit device.

The reason is this description in "HAP-Specification-Non-Commercial-Version.pdf":
``` 
8.9 Current Temperature
...
UUID | 00000011-0000-1000-8000-0026BB765291
...
Minimum Value | 0
```
This was correctly implemented in /homekit/characteristics.h:
```
#define HOMEKIT_CHARACTERISTIC_CURRENT_TEMPERATURE HOMEKIT_APPLE_UUID2("11")
#define HOMEKIT_DECLARE_CHARACTERISTIC_CURRENT_TEMPERATURE(_value, ...) \
    .type = HOMEKIT_CHARACTERISTIC_CURRENT_TEMPERATURE, \
    .description = "Current Temperature", \
  ...  
  .min_value = (float[]) {0}, \  
```
It is necessary to change this:
```
#define HOMEKIT_CHARACTERISTIC_CURRENT_TEMPERATURE HOMEKIT_APPLE_UUID2("11")
#define HOMEKIT_DECLARE_CHARACTERISTIC_CURRENT_TEMPERATURE(_value, ...) \
    .type = HOMEKIT_CHARACTERISTIC_CURRENT_TEMPERATURE, \
    .description = "Current Temperature", \
  ...  
  .min_value = (float[]) {-100}, \  
```
After the change everything worked fine.

**Comment by maximkulkin** [comment]
These characteristics are defined as they are defined in Apple HAP specification. But anyways, you should be able to customize it on the spot, without having to change eps-homekit code:
```c
HOMEKIT_CHARACTERISTIC(CURRENT_TEMPERATURE, 22, .min_value=(float[]) {-100}),
```
