### ISSUE TITLE
cannot build esp32 example

### ISSUE THREAD

**Issue by mentaluproar** [maximkulkin/esp-homekit#95]
in trying to build the esp32/led example, the build failed with the following error:
CC examples/esp32/led/build/homekit/src/storage.o
/home/sean/Downloads/esp-homekit-demo/components/common/homekit/src/storage.c: In function 'homekit_storage_init':
/home/sean/Downloads/esp-homekit-demo/components/common/homekit/src/storage.c:56:38: error: argument to 'sizeof' in 'strncpy' call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
         strncpy(magic, magic1, sizeof(magic1));

help?

**Comment by konifer44** [comment]
Same here ☹️

**Comment by maximkulkin** [comment]
Fixed
